import random

# A simple python Script for a database project.
# It creates a list in this form "(reservation_id, res_name, res_lastname, res_offer_id, adv_pay)" with random data.
# We can then insert the record in the database.
# For our project we needed 60.000 records.
# reservation_id = is a counter.
# res_name = the name of the person.
# res_lastname = the lastname of the person.
# res_offer_id = the reservation offer id.
# adv_pay = the payment in advance.


num = 1
while num <= 60000:

    namelist = ["Emily", "Madison", "Ashley", "Sarah", "Jessica", "Brianna", "Jordan", "Taylor", "Hannah", "Alexis", "Samantha", "Rachel", "Amber", "Megan", "Alyssa", "Lauren", "Victoria", "Diana", "Maria", "Evelyn", "Elizabeth", "Kayla", "Annabelle", "Mackenzie", "Nicole", "Bailey", "Paige", "Jacqueline", "Caitlin", "Jasmine", "Kaitlyn", "Savannah", "Katherine", "Sofia", "Avery", "Brooklyn", "Eleanor", "Adriana", "Gianna", "Jenna", "Kimberly", "Makayla", "Bella", "Aaliyah", "Allison", "Claire", "Mikayla", "Maria", "Aurora", "Aurora", "Isabella", "Maria", "Aurora", "Sofia", "Isabella", "Mia", "Camila", "Valentina", "Natalia", "Luciana", "Valeria", "Adriana", "Ximena", "Julieta", "Daniela", "Gabriela", "Alondra", "Brenda", "Carmen", "Gabriela", "Liliana", "Paulina", "Miranda", "Dulce", "Esperanza", "Guadalupe", "Karina", "Lourdes", "Rosa", "Salvador", "Adela", "Fatima", "Jazmin", "Jimena", "Juana", "Karen", "Leticia", "Luz", "Magdalena", "Maria", "Maya", "Mireya", "Paula", "Rebeca", "Rocio", "Sandra", "Sofia", "Teresa", "Violeta", "Ai", "Aiko", "Aileen", "Aimee", "Airi", "Akane", "Aki", "Akiko", "Akira", "Ako", "Ami", "Aya", "Ayano", "Eri", "Haruka", "Hikari", "Hina", "Hinata", "Hiroko", "Hitomi", "Honoka", "Hotaru", "Ichiro", "Ikuo", "Jiro", "Kaede", "Kaito", "Kana", "Kanako",
                "Kazuko", "Keiko", "Kimi", "Kosuke", "Makoto", "Mami", "Masako", "Masami", "Maya", "Miyuki", "Nao", "Naoko", "Naomi", "Natsu", "Natsumi", "Noboru", "Noriko", "Reiko", "Rika", "Riku", "Rina", "Sachiko", "Saki", "Sakura", "Satomi", "Takako", "Takashi", "Taro", "Aarav", "Aryan", "Abhinav", "Aditya", "Aryan", "Amit", "Aniket", "Arnav", "Arjun", "Arvind", "Aryan", "Ashwin", "Bhavesh", "Chandan", "Devansh", "Dhruv", "Divyansh", "Gaurav", "Hrithik", "Ishaan", "Ishan", "Kunal", "Kush", "Lakshya", "Naveen", "Nimit", "Nirav", "Parth", "Pranav", "Rishabh", "Rohan", "Sahil", "Saksham", "Sarvesh", "Shivansh", "Shivendra", "Shivansh", "Shreyas", "Siddharth", "Sohan", "Sudhanshu", "Suyash", "Tushar", "Uttam", "Ved", "Vivaan", "Yash", "Yogesh", "Alexander", "Anastasia", "Andrei", "Anna", "Anton", "Dmitri", "Ekaterina", "Elena", "Evgeni", "Galina", "Igor", "Irina", "Kirill", "Konstantin", "Larisa", "Maria", "Mikhail", "Natalia", "Nikolai", "Olga", "Pavel", "Sergei", "Sofia", "Tatiana", "Vadim", "Valeria", "Vasili", "Vera", "Victor", "Vladimir", "Yaroslav", "Yulia", "Yuri", "Zhanna", "Alyona", "Anastasiya", "Andrey", "Anzhelika", "Artyom", "Darya", "Dmitriy", "Egor", "Elizaveta", "Evdokiya", "Grigory", "Inna", "Ivan", "Ksenia", "Mariya", "Maxim", "Mikhail", "Nadezhda", "Natalya", "Nikolay"]
    lastnamelist = ["Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King", "Wright", "Lopez", "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Stewart", "Flores", "Morris", "Nguyen", "Garcia", "Gonzalez", "Rodriguez", "Fernandez", "Lopez", "Martinez", "Sanchez", "Perez", "Gomez", "Martín", "Jiménez", "Hernández", "Díaz", "Moreno", "Álvarez", "Muñoz", "Romero", "Alonso", "Gutiérrez", "Navarro", "Torres", "Domínguez", "Vázquez", "Ramos", "Gil", "Ramírez", "Serrano", "Blanco", "Suarez", "Molina", "Morales", "Ortiz", "Rubio", "Marin", "Sanz", "Nuñez", "Iglesias", "Medina", "Garrido", "Cortes", "Castro", "Ortega", "Diez", "Cabrera", "Rey", "Herrera", "Victoria", "Muñoz", "Peña", "Cano", "Lozano", "Castillo", "Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Hong", "Yoon", "Ahn", "Cho", "Lim", "Shim", "Shin", "Yoo", "Yoon", "Wang", "Lin", "Chen", "Chang", "Chou", "Liu", "Huang",
                    "Tsai", "Hsu", "Wu", "Lin", "Chu", "Cheng", "Chen", "Liu", "Lo", "Luo", "Zheng", "Zhang", "Zhou", "Xu", "Wu", "Tu", "Tang", "Shi", "Qin", "Pan", "Liang", "Jiang", "Hu", "Feng", "Dong", "Cao", "Chen", "Kumar", "Sharma", "Gupta", "Singh", "Patel", "Kapoor", "Chauhan", "Verma", "Yadav", "Jha", "Ahuja", "Nayar", "Rao", "Khan", "Mehra", "Reddy", "Das", "Malik", "Chopra", "Gandhi", "Bose", "Bhat", "Varma", "Bhushan", "Mahajan", "Prakash", "Seth", "Mathur", "Shankar", "Srivastava", "Agarwal", "Agrawal", "Nair", "Menon", "Shukla", "Tiwari", "Dutt", "Jain", "Dasgupta", "Kaul", "Saraf", "Sarin", "Sethi", "Somaiya", "Suri", "Swamy", "Vaidya", "Vyas", "Mehta", "Tandon", "Nagpal", "Ivanov", "Smirnov", "Kuznetsov", "Popov", "Vasiliev", "Sokolov", "Mikhailov", "Lebedev", "Kovalev", "Grigoriev", "Egorov", "Pavlov", "Morozov", "Zhukov", "Fedorov", "Kozlov", "Novikov", "Konovalov", "Tkachev", "Shchukin", "Shapovalov", "Rozhkov", "Krylov", "Korolev", "Belov", "Volkov", "Solovyev", "Bogdanov", "Andreyev", "Polyakov", "Vinogradov", "Medvedev", "Kozhin", "Lisitsyn", "Koshelev", "Kolosov", "Kolomiytsev", "Khokhlov", "Kazakov", "Kashin", "Kapustin", "Ivanenko", "Gusev", "Danilov", "Chernyshev", "Bryzgalov", "Boyko", "Andrianov", "Aleksandrov"]
    reservation_id = num
    res_name = random.choice(namelist)
    res_lastname = random.choice(lastnamelist)
    res_offer_id = 1
    adv_pay = random.randint(50, 200)
    list = (reservation_id, res_name, res_lastname, res_offer_id, adv_pay)
    print(list, ',')
    num = num + 1
